version: '2.1'

services:

  app:
    image: ${DC_IMAGE}
    command:
      /opt/macobot/macobot --addr ${ADDR} --login ${LOGIN} --password ${PASSWORD} --team ${TEAM} --channel ${CHANNEL} 
      --command /opt/macobot/script/macobot.sh ${ADD}
    networks:
      - web
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - .:/opt/macobot/script:ro
    build:
      context: .

networks:
  web:
    external:
      name: ${DCAPE_NET}
