CFG           ?= .env
STAMP     ?= $$(date +%Y-%m-%d_%H:%M.%S)

# ------------------------------------------------------------------------------

# Файл .env
define CONFIG_DEF
# config file, generated by make .env

# Default


endef
export CONFIG_DEF

-include $(CFG)
export

# -----------------------------------------------------------------------------
# default: show target list
all: help

# -----------------------------------------------------------------------------

.PHONY: run

# Golang Flags
GOPATH ?= $(GOPATH:):./vendor
GOFLAGS ?= $(GOFLAGS:)
GO=go

.prebuild:
	@echo Preparation for running go code
	go get $(GOFLAGS) github.com/Masterminds/glide

	touch $@

run:
	@echo "*** $@ ***"
	@[ -d $(GIT_ROOT)/.git ] && GH=`git rev-parse HEAD` || GH=nogit ; \
	$(GO) run $(GOFLAGS) $(GO_LINKER_FLAGS) -ldflags \
  "-X main.Build=$(STAMP) -X main.Commit=$$GH" *.go \
  --addr $(ADDR) --login $(LOGIN) --password $(PASSWORD) --team $(TEAM) --channel $(CHANNEL)

# -----------------------------------------------------------------------------

## Show available make targets
help:
	@grep -A 1 "^##" Makefile | less

## Generate default config
$(CFG):
	@echo "*** $@ ***"
	@echo "$$CONFIG_DEF" > $@

## Create default $(CFG) file
config:
	@true
